
spring:
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
  application:
    name: teste-api
  servlet:
    multipart:
      max-file-size: 50MB
  datasource:
    url: jdbc:mysql://localhost:3306/lampp-it
    username: user
    password: password

  jpa:
    show-sql: true
server:
  port: 8080
  error:
    include-stacktrace: never

allowedHosts: http://localhost:4200,*