use `lampp-it`;

CREATE TABLE IF NOT EXISTS user_system (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  email VARCHAR(255) NOT NULL UNIQUE,
  password VARCHAR(100) NOT NULL,
  role ENUM('CUSTOMER', 'DELIVERY_PERSON', 'COMPANY')
);
